In [62]:
import pandas as pd
import numpy as np

In [63]:
data_df=pd.read_csv('../urls.csv')

In [64]:
data_df.head()

,crs_id,crs_title,file_id,file_name,file_url
0,1,Chapter 6 (Addition and Subtraction) (A),Addition 1,(Review up to 2A),https://shikhyaprod.s3.amazonaws.com/odia/Cour...
1,2,Chapter 6 (Addition and Subtraction) (A),Addition 2,(Up to sum of 12),https://shikhyaprod.s3.amazonaws.com/odia/Cour...
2,3,Chapter 6 (Addition and Subtraction) (A),Addition 3,(Up to sum of 15),https://shikhyaprod.s3.amazonaws.com/odia/Cour...
3,4,Chapter 6 (Addition and Subtraction) (A),Addition 4,(Up to sum of 18),https://shikhyaprod.s3.amazonaws.com/odia/Cour...
4,5,Chapter 6 (Addition and Subtraction) (A),Addition 5,(Up to sum of 20),https://shikhyaprod.s3.amazonaws.com/odia/Cour...

In [65]:
data_df['file_name'] = data_df['file_name'].apply(lambda x: x.replace(' ', '_') if isinstance(x, str) else x)
data_df['crs_title'] = data_df['crs_title'].apply(lambda x: x.replace(' ', '_') if isinstance(x, str) else x)
print(data_df['file_name'])

0     (Review_up_to_2A)
1     (Up_to_sum_of_12)
2     (Up_to_sum_of_15)
3     (Up_to_sum_of_18)
4     (Up_to_sum_of_20)
            ...
75                   00
76                    1
77                    2
78                    3
79                    4
Name: file_name, Length: 80, dtype: object

In [66]:
data_df.sample(n=2)

,crs_id,crs_title,file_id,file_name,file_url
6,7,Chapter_6__(Addition_and_Subtraction)_(A),Addition 7,(Up_to_sum_of_28),https://shikhyaprod.s3.amazonaws.com/odia/Cour...
35,36,Chapter_7__(_Two_Digit_Addition)_B,Subtraction of,3-Digit_Numbers_1,https://shikhyaprod.s3.amazonaws.com/odia/Cour...

In [67]:
data_df['final_name'] = data_df['crs_id'].astype(str) + '_' + data_df['crs_title'].astype(str) + '_' + data_df['file_id'].astype(str) + '_' + data_df['file_name']

In [68]:
data_df.head()

,crs_id,crs_title,file_id,file_name,file_url,final_name
0,1,Chapter_6__(Addition_and_Subtraction)_(A),Addition 1,(Review_up_to_2A),https://shikhyaprod.s3.amazonaws.com/odia/Cour...,1_Chapter_6__(Addition_and_Subtraction)_(A)_Ad...
1,2,Chapter_6__(Addition_and_Subtraction)_(A),Addition 2,(Up_to_sum_of_12),https://shikhyaprod.s3.amazonaws.com/odia/Cour...,2_Chapter_6__(Addition_and_Subtraction)_(A)_Ad...
2,3,Chapter_6__(Addition_and_Subtraction)_(A),Addition 3,(Up_to_sum_of_15),https://shikhyaprod.s3.amazonaws.com/odia/Cour...,3_Chapter_6__(Addition_and_Subtraction)_(A)_Ad...
3,4,Chapter_6__(Addition_and_Subtraction)_(A),Addition 4,(Up_to_sum_of_18),https://shikhyaprod.s3.amazonaws.com/odia/Cour...,4_Chapter_6__(Addition_and_Subtraction)_(A)_Ad...
4,5,Chapter_6__(Addition_and_Subtraction)_(A),Addition 5,(Up_to_sum_of_20),https://shikhyaprod.s3.amazonaws.com/odia/Cour...,5_Chapter_6__(Addition_and_Subtraction)_(A)_Ad...

In [69]:
list_of_urls_to_download = dict(zip(data_df['final_name'], data_df['file_url']))

In [70]:
list_of_urls_to_download

{'1_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 1 _(Review_up_to_2A)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2659/2659_rMhTpeMQQu.pdf',
 '2_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 2 _(Up_to_sum_of_12)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2660/2660_qiuBptpaBu.pdf',
 '3_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 3 _(Up_to_sum_of_15)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2661/2661_rDZZRCoC91.pdf',
 '4_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 4 _(Up_to_sum_of_18)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2662/2662_2JH6d3zl5G.pdf',
 '5_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 5 _(Up_to_sum_of_20)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2663/2663_meOjF0xIhk.pdf',
 '6_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 6 _(Up_to_sum_of_24)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2664/2664_reLQ8A0Oy5.pdf',
 '7_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 7 _(Up_to_sum_of_28)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2665/2665_sHBXexJWKI.pdf',
 '8_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 8 _(Summary_of_addition)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2666/2666_FeIlsgFrcf.pdf',
 '9_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 1 _(Subtracting_1)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2667/2667_7bqagbZD2v.pdf',
 '10_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 2 _(Subtracting_2)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2668/2668_ekvA35jTlp.pdf',
 '11_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 3 _(Subtracting_3)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2669/2669_S6g49pIB9G.pdf',
 '12_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 4 _(Subtracting_up_to_3)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2670/2670_ieT6T8ZNXT.pdf',
 '13_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 5 _(Subtracting_up_to_5)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2671/2671_Dr8jY3XHbp.pdf',
 '14_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 6 _(From_numbers_up_to_10)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2672/2672_ka7TvrSBrf.pdf',
 '15_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 7 _(From_numbers_up_to_11)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2673/2673_d2gCWUX1es.pdf',
 '16_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 8 _(From_numbers_up_to_12)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2674/2674_MEIp2xkWvA.pdf',
 '17_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 9 _(From_numbers_up_to_14)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2675/2675_Nu8LsZqzdk.pdf',
 '18_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 10 _(From_numbers_up_to_16)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2676/2676_mEVNNyOSMJ.pdf',
 '19_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 11 _(From_numbers_up_to_20)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2677/2677_yd5k4BMvJp.pdf',
 '20_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 12 _(Summary_of_subtraction)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/241/files/2678/2678_BwHJGTluVG.pdf',
 '21_Chapter_7__(_Two_Digit_Addition)_B_Addition to 100 _Part_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2680/2680_JdXcn49dVv.pdf',
 '22_Chapter_7__(_Two_Digit_Addition)_B_Addition to 100 _Part_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2681/2681_2ySvr7QZo6.pdf',
 '23_Chapter_7__(_Two_Digit_Addition)_B_Addition to 100 _Part_3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2682/2682_5H5l3ZeZ5P.pdf',
 '24_Chapter_7__(_Two_Digit_Addition)_B_Addition of _2-Digit_Numbers_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2683/2683_b0CNhLTVD1.pdf',
 '25_Chapter_7__(_Two_Digit_Addition)_B_Addition of _2-Digit_Numbers_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2684/2684_kpRQWLf2Bm.pdf',
 '26_Chapter_7__(_Two_Digit_Addition)_B_Addition of _2-Digit_Numbers_3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2685/2685_oOxMkHLbzN.pdf',
 '27_Chapter_7__(_Two_Digit_Addition)_B_Addition of _3-Digit_Numbers_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2686/2686_zlXKLWuk4y.pdf',
 '28_Chapter_7__(_Two_Digit_Addition)_B_Addition of _3-Digit_Numbers_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2687/2687_RGQTdPtfNw.pdf',
 '29_Chapter_7__(_Two_Digit_Addition)_B_Addition of _3-Digit_Numbers_3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2688/2688_ldibD1n2qE.pdf',
 '30_Chapter_7__(_Two_Digit_Addition)_B_Subtraction _1_(Review_up_to_A)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2689/2689_UtUdKqCQcC.pdf',
 '31_Chapter_7__(_Two_Digit_Addition)_B_Subtraction _2_(Review_up_to_A)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2690/2690_3VDzYTHmVf.pdf',
 '32_Chapter_7__(_Two_Digit_Addition)_B_Subtraction _of_2-Digit_Numbers_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2691/2691_1mw6M0zPvt.pdf',
 '33_Chapter_7__(_Two_Digit_Addition)_B_Subtraction _of_2-Digit_Numbers_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2692/2692_KZrnuEflgN.pdf',
 '34_Chapter_7__(_Two_Digit_Addition)_B_Subtraction _of_2-Digit_Numbers_3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2693/2693_VHO26D3YWr.pdf',
 '35_Chapter_7__(_Two_Digit_Addition)_B_Addition and _Subtraction_of_2-Digit_Numbers': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2694/2694_ay9flPh0vW.pdf',
 '36_Chapter_7__(_Two_Digit_Addition)_B_Subtraction of _3-Digit_Numbers_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2695/2695_cd8BDwfGv7.pdf',
 '37_Chapter_7__(_Two_Digit_Addition)_B_Subtraction of _3-Digit_Numbers_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2696/2696_LtEd0kvW3e.pdf',
 '38_Chapter_7__(_Two_Digit_Addition)_B_Subtraction of _3-Digit_Numbers_3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2697/2697_OYgiyglV6n.pdf',
 '39_Chapter_7__(_Two_Digit_Addition)_B_Subtraction of _3-Digit_Numbers_4': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2698/2698_ozf3cNoJjJ.pdf',
 '40_Chapter_7__(_Two_Digit_Addition)_B_Addition _(Review_up_to_A)': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/242/files/2679/2679_fsQIfIfr4N.pdf',
 '41_Chapter_8__Multiplication_and_Division_(c)_Review up _to_B': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2565/2565_abH1HTEqop.pdf',
 '42_Chapter_8__Multiplication_and_Division_(c)_Multiplication _up_to_3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2566/2566_JemIg1DIoB.pdf',
 '43_Chapter_8__Multiplication_and_Division_(c)_Multiplication _up_to_5': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2567/2567_l3AyIORjyI.pdf',
 '44_Chapter_8__Multiplication_and_Division_(c)_Multiplication _up_to_7': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2568/2568_qfd80MJKZj.pdf',
 '45_Chapter_8__Multiplication_and_Division_(c)_Multiplication _up_to_9': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2569/2569_BllWRGZgVd.pdf',
 '46_Chapter_8__Multiplication_and_Division_(c)_Multiplication 2 _Digits_&times;_1_Digit_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2570/2570_xCmZbI2tXb.pdf',
 '47_Chapter_8__Multiplication_and_Division_(c)_Multiplication 2 _Digits_&times;_1_Digit_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2571/2571_WgmZtQom2w.pdf',
 '48_Chapter_8__Multiplication_and_Division_(c)_Multiplication 2 _Digits_&times;_1_Digit_3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2572/2572_DMGEYn3nB4.pdf',
 '49_Chapter_8__Multiplication_and_Division_(c)_Multiplication 2 _Digits_&times;_1_Digit_4': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2573/2573_Hl5HfQzO23.pdf',
 '50_Chapter_8__Multiplication_and_Division_(c)_Multiplication 2 _Digits_&times;_1_Digit_5': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2574/2574_p4B99Px0zh.pdf',
 '51_Chapter_8__Multiplication_and_Division_(c)_Multiplication 3 or 4 _Digits_&times;_1_Digit': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2575/2575_y23OewfbIb.pdf',
 '52_Chapter_8__Multiplication_and_Division_(c)_Introduction to _Division': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2576/2576_vHPuIougcS.pdf',
 '53_Chapter_8__Multiplication_and_Division_(c)_Division With _Remainder_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2577/2577_rq0zZrzuG6.pdf',
 '54_Chapter_8__Multiplication_and_Division_(c)_Division with _Remainder_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2578/2578_vnFglTOhSQ.pdf',
 '55_Chapter_8__Multiplication_and_Division_(c)_Division with _Remainder_3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2579/2579_lLRNQ8GmQN.pdf',
 '56_Chapter_8__Multiplication_and_Division_(c)_Division with _Remainder_4': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2580/2580_VQJSxowx8d.pdf',
 '57_Chapter_8__Multiplication_and_Division_(c)_Division 2 Digits _&divide;_1_Digit_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2581/2581_vVGivedgNa.pdf',
 '58_Chapter_8__Multiplication_and_Division_(c)_Division 2 Digits _&divide;_1_Digit_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2582/2582_uKo8hE2DI9.pdf',
 '59_Chapter_8__Multiplication_and_Division_(c)_Division 3 Digits _&divide;_1_Digit_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2583/2583_CjVzBrpRjJ.pdf',
 '60_Chapter_8__Multiplication_and_Division_(c)_Division 3 Digits _&divide;_1_Digit_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/234/files/2584/2584_NdQLlFgt03.pdf',
 '61_Chapter_9__(Multiplication/Division/Fraction)_D_Review _up_to_C': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2699/2699_khyWhG0cjR.pdf',
 '62_Chapter_9__(Multiplication/Division/Fraction)_D_Multiplication: _2_Digits_x_2_Digits_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2700/2700_aCo82oLkHH.pdf',
 '63_Chapter_9__(Multiplication/Division/Fraction)_D_Multiplication: _2_Digits_x_2_Digits_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2701/2701_CjM5AFAIVq.pdf',
 '64_Chapter_9__(Multiplication/Division/Fraction)_D_Multiplication: _2_Digits_x_2_Digits_3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2702/2702_OCAkSAfE0M.pdf',
 '65_Chapter_9__(Multiplication/Division/Fraction)_D_Multiplication: _3_Digits_x_2_Digits': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2703/2703_NjroXklwMW.pdf',
 '66_Chapter_9__(Multiplication/Division/Fraction)_D_Addition and _Subtraction': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2704/2704_lkfsAkhdPH.pdf',
 '67_Chapter_9__(Multiplication/Division/Fraction)_D_Multiplication and _Division_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2705/2705_lWUcCr4vmD.pdf',
 '68_Chapter_9__(Multiplication/Division/Fraction)_D_Multiplication and _Division_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2706/2706_uHQHdESLnn.pdf',
 '69_Chapter_9__(Multiplication/Division/Fraction)_D_Division by _2-Digit_Numbers_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2707/2707_kmqjLZUqA7.pdf',
 '70_Chapter_9__(Multiplication/Division/Fraction)_D_Division by _2-Digit_Numbers_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2708/2708_NczjSzivqo.pdf',
 '71_Chapter_9__(Multiplication/Division/Fraction)_D_Division by _2-Digit_Numbers_3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2709/2709_X7jbA05vSx.pdf',
 '72_Chapter_9__(Multiplication/Division/Fraction)_D_Division by _2-Digit_Numbers_4': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2710/2710_1B49ZorYtO.pdf',
 '73_Chapter_9__(Multiplication/Division/Fraction)_D_Division by _2-Digit_Numbers_5': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2711/2711_XjK6iuFOfd.pdf',
 '74_Chapter_9__(Multiplication/Division/Fraction)_D_Division: _Quotients_of_2-or-More_Digits_1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2712/2712_XhsJBkOzcC.pdf',
 '75_Chapter_9__(Multiplication/Division/Fraction)_D_Division: _Quotients_of_2-or-More_Digits_2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2713/2713_Z7Q6axZmjW.pdf',
 '76_Chapter_9__(Multiplication/Division/Fraction)_D_Fractions _00': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2714/2714_fhEnEjPeYJ.pdf',
 '77_Chapter_9__(Multiplication/Division/Fraction)_D_Reduction _1': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2715/2715_jofKlq1g1N.pdf',
 '78_Chapter_9__(Multiplication/Division/Fraction)_D_Reduction _2': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2716/2716_oM5lKxiU93.pdf',
 '79_Chapter_9__(Multiplication/Division/Fraction)_D_Reduction _3': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2717/2717_3ifnrFHnoK.pdf',
 '80_Chapter_9__(Multiplication/Division/Fraction)_D_Reduction _4': 'https://shikhyaprod.s3.amazonaws.com/odia/CourseResource/243/files/2718/2718_krabyHCmFF.pdf'}

In [71]:
import os
import requests

# Folder to save PDFs
save_folder = "downloads"
os.makedirs(save_folder, exist_ok=True)

def download_pdf(url, save_path):
    """Download a PDF file from a given URL and save it."""
    try:
        response = requests.get(url, stream=True)
        response.raise_for_status()  # Raise an error for bad responses (4xx, 5xx)
        
        with open(save_path, "wb") as file:
            for chunk in response.iter_content(chunk_size=8192):
                file.write(chunk)
        
        print(f"Downloaded: {save_path}")
    except requests.exceptions.RequestException as e:
        print(f"Failed to download {url}: {e}")

for final_name, url in list_of_urls_to_download.items():
    save_path = os.path.join(save_folder, final_name + ".pdf")  # Use the key as the filename
    download_pdf(url, save_path)

print("Download process completed.")

Downloaded: downloads/1_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 1 _(Review_up_to_2A).pdf
Downloaded: downloads/2_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 2 _(Up_to_sum_of_12).pdf
Downloaded: downloads/3_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 3 _(Up_to_sum_of_15).pdf
Downloaded: downloads/4_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 4 _(Up_to_sum_of_18).pdf
Downloaded: downloads/5_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 5 _(Up_to_sum_of_20).pdf
Downloaded: downloads/6_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 6 _(Up_to_sum_of_24).pdf
Downloaded: downloads/7_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 7 _(Up_to_sum_of_28).pdf
Downloaded: downloads/8_Chapter_6__(Addition_and_Subtraction)_(A)_Addition 8 _(Summary_of_addition).pdf
Downloaded: downloads/9_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 1 _(Subtracting_1).pdf
Downloaded: downloads/10_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 2 _(Subtracting_2).pdf
Downloaded: downloads/11_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 3 _(Subtracting_3).pdf
Downloaded: downloads/12_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 4 _(Subtracting_up_to_3).pdf
Downloaded: downloads/13_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 5 _(Subtracting_up_to_5).pdf
Downloaded: downloads/14_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 6 _(From_numbers_up_to_10).pdf
Downloaded: downloads/15_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 7 _(From_numbers_up_to_11).pdf
Downloaded: downloads/16_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 8 _(From_numbers_up_to_12).pdf
Downloaded: downloads/17_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 9 _(From_numbers_up_to_14).pdf
Downloaded: downloads/18_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 10 _(From_numbers_up_to_16).pdf
Downloaded: downloads/19_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 11 _(From_numbers_up_to_20).pdf
Downloaded: downloads/20_Chapter_6__(Addition_and_Subtraction)_(A)_Subtraction 12 _(Summary_of_subtraction).pdf
Downloaded: downloads/21_Chapter_7__(_Two_Digit_Addition)_B_Addition to 100 _Part_1.pdf
Downloaded: downloads/22_Chapter_7__(_Two_Digit_Addition)_B_Addition to 100 _Part_2.pdf
Downloaded: downloads/23_Chapter_7__(_Two_Digit_Addition)_B_Addition to 100 _Part_3.pdf
Downloaded: downloads/24_Chapter_7__(_Two_Digit_Addition)_B_Addition of _2-Digit_Numbers_1.pdf
Downloaded: downloads/25_Chapter_7__(_Two_Digit_Addition)_B_Addition of _2-Digit_Numbers_2.pdf
Downloaded: downloads/26_Chapter_7__(_Two_Digit_Addition)_B_Addition of _2-Digit_Numbers_3.pdf
Downloaded: downloads/27_Chapter_7__(_Two_Digit_Addition)_B_Addition of _3-Digit_Numbers_1.pdf
Downloaded: downloads/28_Chapter_7__(_Two_Digit_Addition)_B_Addition of _3-Digit_Numbers_2.pdf
Downloaded: downloads/29_Chapter_7__(_Two_Digit_Addition)_B_Addition of _3-Digit_Numbers_3.pdf
Downloaded: downloads/30_Chapter_7__(_Two_Digit_Addition)_B_Subtraction _1_(Review_up_to_A).pdf
Downloaded: downloads/31_Chapter_7__(_Two_Digit_Addition)_B_Subtraction _2_(Review_up_to_A).pdf
Downloaded: downloads/32_Chapter_7__(_Two_Digit_Addition)_B_Subtraction _of_2-Digit_Numbers_1.pdf
Downloaded: downloads/33_Chapter_7__(_Two_Digit_Addition)_B_Subtraction _of_2-Digit_Numbers_2.pdf
Downloaded: downloads/34_Chapter_7__(_Two_Digit_Addition)_B_Subtraction _of_2-Digit_Numbers_3.pdf
Downloaded: downloads/35_Chapter_7__(_Two_Digit_Addition)_B_Addition and _Subtraction_of_2-Digit_Numbers.pdf
Downloaded: downloads/36_Chapter_7__(_Two_Digit_Addition)_B_Subtraction of _3-Digit_Numbers_1.pdf
Downloaded: downloads/37_Chapter_7__(_Two_Digit_Addition)_B_Subtraction of _3-Digit_Numbers_2.pdf
Downloaded: downloads/38_Chapter_7__(_Two_Digit_Addition)_B_Subtraction of _3-Digit_Numbers_3.pdf
Downloaded: downloads/39_Chapter_7__(_Two_Digit_Addition)_B_Subtraction of _3-Digit_Numbers_4.pdf
Downloaded: downloads/40_Chapter_7__(_Two_Digit_Addition)_B_Addition _(Review_up_to_A).pdf
Downloaded: downloads/41_Chapter_8__Multiplication_and_Division_(c)_Review up _to_B.pdf
Downloaded: downloads/42_Chapter_8__Multiplication_and_Division_(c)_Multiplication _up_to_3.pdf
Downloaded: downloads/43_Chapter_8__Multiplication_and_Division_(c)_Multiplication _up_to_5.pdf
Downloaded: downloads/44_Chapter_8__Multiplication_and_Division_(c)_Multiplication _up_to_7.pdf
Downloaded: downloads/45_Chapter_8__Multiplication_and_Division_(c)_Multiplication _up_to_9.pdf
Downloaded: downloads/46_Chapter_8__Multiplication_and_Division_(c)_Multiplication 2 _Digits_&times;_1_Digit_1.pdf
Downloaded: downloads/47_Chapter_8__Multiplication_and_Division_(c)_Multiplication 2 _Digits_&times;_1_Digit_2.pdf
Downloaded: downloads/48_Chapter_8__Multiplication_and_Division_(c)_Multiplication 2 _Digits_&times;_1_Digit_3.pdf
Downloaded: downloads/49_Chapter_8__Multiplication_and_Division_(c)_Multiplication 2 _Digits_&times;_1_Digit_4.pdf
Downloaded: downloads/50_Chapter_8__Multiplication_and_Division_(c)_Multiplication 2 _Digits_&times;_1_Digit_5.pdf
Downloaded: downloads/51_Chapter_8__Multiplication_and_Division_(c)_Multiplication 3 or 4 _Digits_&times;_1_Digit.pdf
Downloaded: downloads/52_Chapter_8__Multiplication_and_Division_(c)_Introduction to _Division.pdf
Downloaded: downloads/53_Chapter_8__Multiplication_and_Division_(c)_Division With _Remainder_1.pdf
Downloaded: downloads/54_Chapter_8__Multiplication_and_Division_(c)_Division with _Remainder_2.pdf
Downloaded: downloads/55_Chapter_8__Multiplication_and_Division_(c)_Division with _Remainder_3.pdf
Downloaded: downloads/56_Chapter_8__Multiplication_and_Division_(c)_Division with _Remainder_4.pdf
Downloaded: downloads/57_Chapter_8__Multiplication_and_Division_(c)_Division 2 Digits _&divide;_1_Digit_1.pdf
Downloaded: downloads/58_Chapter_8__Multiplication_and_Division_(c)_Division 2 Digits _&divide;_1_Digit_2.pdf
Downloaded: downloads/59_Chapter_8__Multiplication_and_Division_(c)_Division 3 Digits _&divide;_1_Digit_1.pdf
Downloaded: downloads/60_Chapter_8__Multiplication_and_Division_(c)_Division 3 Digits _&divide;_1_Digit_2.pdf

FileNotFoundError: [Errno 2] No such file or directory: 'downloads/61_Chapter_9__(Multiplication/Division/Fraction)_D_Review _up_to_C.pdf'